### ISSUE TITLE
Data type inconsistency in handle_subflow

### ISSUE THREAD

**Issue by mjmartineau** [intel/mptcpd#26]
**Describe the bug**
The `token` parameter to `handle_subflow()` is causing a compile error at line 599 in `handle_subflow()`, where there's a mismatch between the formatting specifier and the `token` variable.

Should the second parameter to the function be a `mptcp_token_t const *token`, with callers of `handle_subflow()` providing storage for a mptcp_token_t on the stack? It does look like the current approach should work (other than the debug statement), since the `l_genl_msg` remains valid in the callers of `handle_subflow()` - so the minimal fix is to add a `*` in the debug statement at line 599 and change the `!token` to `!*token` at line 588.

**To Reproduce**
1. Build using gcc 9.1.1

**Expected behavior**
No compile error

**Desktop (please complete the following information):**
 - Linux Kernel: 5.1.5
 - Compiler: gcc 9.1.1

**Comment by ossama-othman** [comment]
I just reproduced the error with Clang 8, too:

```c
  CC       libpath_manager_la-path_manager.lo
path_manager.c:593:48: error: format specifies type 'unsigned int' but the
      argument has type 'const mptcpd_token_t *' (aka 'const unsigned int *')
      [-Werror,-Wformat]
        l_debug("token: 0x%" MPTCPD_PRIxTOKEN, *token);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/usr/local/include/ell/log.h:95:70: note: expanded from macro 'l_debug'
  ......)  L_DEBUG_SYMBOL(__debug_desc, format, ##__VA_ARGS__)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
/usr/local/include/ell/log.h:72:19: note: expanded from macro 'L_DEBUG_SYMBOL'
                                        __func__ , ##__VA_ARGS__); \
                                        ~~~~~~~~~~~~~^~~~~~~~~~~~
/usr/local/include/ell/log.h:54:31: note: expanded from macro 'l_log'
                                        __func__, format "\n", ##__VA_ARGS__)
                                                  ~~~~~~         ^~~~~~~~~~~
1 error generated.

**Comment by ossama-othman** [comment]
You're right about the type inconsistency.   The token parameter should indeed be `mptcp_token_t const *token`.  I'll push a patch shortly.

**Comment by ossama-othman** [comment]
On second thought.  I think the correction I just pushed is actually wrong, and that the original type `mptcpd_token_t const **` was correct since `l_genl_attr_next()` passes a pointer to the attribute back to the caller, not a copy of the value.  The token value will not be propagated to the functions that call `handle_subflow()` with the current change in place.

**Comment by ossama-othman** [comment]
I'll generate some subflow events and confirm.

**Comment by mjmartineau** [comment]
I was assuming there would be a local pointer to have `l_genl_attr_next()` set, with the pointed-to value copied using the output pointer (much like the other output parameters for `handle_subflow()` and similar functions

**Comment by ossama-othman** [comment]
Do you mean something like the following?

```diff
diff --git a/src/path_manager.c b/src/path_manager.c
index 5c01987..342fe32 100644
--- a/src/path_manager.c
+++ b/src/path_manager.c
@@ -503,7 +503,7 @@ static void handle_addr_removed(struct l_genl_msg *msg, void *user_data)
  * @return @c true on success, @c false otherwise.
  */
 static bool handle_subflow(struct l_genl_msg *msg,
-                           mptcpd_token_t const **token,
+                           mptcpd_token_t *token,
                            struct mptcpd_addr *laddr,
                            struct mptcpd_addr *raddr,
                            bool *backup)
@@ -532,7 +532,7 @@ static bool handle_subflow(struct l_genl_msg *msg,
               Error (optional)
          */
 
-        *token                             = NULL;
+        mptcpd_token_t  const *tok         = NULL;
         struct in_addr  const *laddr4      = NULL;
         struct in_addr  const *raddr4      = NULL;
         struct in6_addr const *laddr6      = NULL;
@@ -548,7 +548,7 @@ static bool handle_subflow(struct l_genl_msg *msg,
         while (l_genl_attr_next(&attr, &type, &len, &data)) {
                 switch (type) {
                 case MPTCP_ATTR_TOKEN:
-                        MPTCP_GET_NL_ATTR(data, len, *token);
+                        MPTCP_GET_NL_ATTR(data, len, tok);
                         break;
                 case MPTCP_ATTR_SADDR4:
                         MPTCP_GET_NL_ATTR(data, len, laddr4);
@@ -579,7 +579,7 @@ static bool handle_subflow(struct l_genl_msg *msg,
                 }
         }
 
-        if (!*token
+        if (!tok
             || !(laddr4 || laddr6)
             || !local_port
             || !(raddr4 || raddr6)
@@ -591,7 +591,9 @@ static bool handle_subflow(struct l_genl_msg *msg,
                 return false;
         }
 
-        l_debug("token: 0x%" MPTCPD_PRIxTOKEN, **token);
+        *token = *tok;
+
+        l_debug("token: 0x%" MPTCPD_PRIxTOKEN, *token);
 
         get_mptcpd_addr(laddr4, laddr6, *local_port,  laddr);
         get_mptcpd_addr(raddr4, raddr6, *remote_port, raddr);
@@ -616,7 +618,7 @@ static void handle_new_subflow(struct l_genl_msg *msg, void *user_data)
               Error (optional)
          */
 
-        mptcpd_token_t const *token  = NULL;
+        mptcpd_token_t token = 0;
         struct mptcpd_addr laddr;
         struct mptcpd_addr raddr;
         bool backup = false;
@@ -626,7 +628,7 @@ static void handle_new_subflow(struct l_genl_msg *msg, void *user_data)
 
         struct mptcpd_pm *const pm = user_data;
 
-        mptcpd_plugin_new_subflow(*token, &laddr, &raddr, backup, pm);
+        mptcpd_plugin_new_subflow(token, &laddr, &raddr, backup, pm);
 }
 
 static void handle_subflow_closed(struct l_genl_msg *msg, void *user_data)
@@ -644,7 +646,7 @@ static void handle_subflow_closed(struct l_genl_msg *msg, void *user_data)
               Error (optional)
          */
 
-        mptcpd_token_t const *token  = NULL;
+        mptcpd_token_t token = 0;
         struct mptcpd_addr laddr;
         struct mptcpd_addr raddr;
         bool backup = false;
@@ -654,7 +656,7 @@ static void handle_subflow_closed(struct l_genl_msg *msg, void *user_data)
 
         struct mptcpd_pm *const pm = user_data;
 
-        mptcpd_plugin_subflow_closed(*token, &laddr, &raddr, backup, pm);
+        mptcpd_plugin_subflow_closed(token, &laddr, &raddr, backup, pm);
 }
 
 static void handle_priority_changed(struct l_genl_msg *msg,
@@ -673,7 +675,7 @@ static void handle_priority_changed(struct l_genl_msg *msg,
               Error (optional)
          */
 
-        mptcpd_token_t const *token  = NULL;
+        mptcpd_token_t token = 0;
         struct mptcpd_addr laddr;
         struct mptcpd_addr raddr;
         bool backup = false;
@@ -683,11 +685,7 @@ static void handle_priority_changed(struct l_genl_msg *msg,
 
         struct mptcpd_pm *const pm = user_data;
 
-        mptcpd_plugin_subflow_priority(*token,
-                                       &laddr,
-                                       &raddr,
-                                       backup,
-                                       pm);
+        mptcpd_plugin_subflow_priority(token, &laddr, &raddr, backup, pm);
 }
 
 static void handle_mptcp_event(struct l_genl_msg *msg, void *user_data)
```

**Comment by mjmartineau** [comment]
Yeah, that's what I was referring to

**Comment by ossama-othman** [comment]
Okay.  I'll push the above patch.  Thanks again!

**Comment by ossama-othman** [comment]
Pushed.  See 1efc117.
